[versions]
agp = "8.13.1"
protobuf = "0.9.5"
kotlin = "2.2.21"
appcompat = "1.7.1"
baselineprofile = "1.4.1"
core = "1.17.0"
annotation = "1.9.1"
coreAnimation = "1.0.0"
dagger = "2.57.2"
dexmaker = "1.2"
dexmakerMockito = "1.2"
dynamicanimation = "1.1.0"
graphicsShapes = "1.1.0"
junitVersion = "1.3.0"

# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.10.2"

# https://github.com/JetBrains/compose-multiplatform
compose = "1.9.3"
lifecycle = "2.9.1"
lottie = "6.7.1"
material = "1.13.0"
material3Version = "1.4.0"
mockitoCore = "5.20.0"
navigation = "2.9.1"

coil = "3.3.0"
kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.7.1"
preference = "1.2.1"
protobufJavalite = "4.33.2"
recyclerview = "1.4.0"
robolectric = "4.16"
rulesVersion = "1.7.0"
runner = "1.0.2"
rules = "1.0.2"
sliceBuilders = "1.0.0"

junit = "4.13.2"

# https://mvnrepository.com/artifact/com.igormaznitsa/meta-annotations
meta-annotations = "1.1.3"
# https://mvnrepository.com/artifact/com.igormaznitsa/meta-utils
meta-utils = "1.1.3"
# https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
commons-lang3 = "3.14.0"
# https://mvnrepository.com/artifact/commons-io/commons-io
commons-io = "2.15.1"
# https://mvnrepository.com/artifact/org.apache.commons/commons-compress
commons-compress = "1.26.1"
# https://mvnrepository.com/artifact/org.json/json
gson = "2.13.2"
# https://mvnrepository.com/artifact/org.dom4j/dom4j
dom4j = "2.1.4"
# https://mvnrepository.com/artifact/org.json/json
json = "20250517"
# https://mvnrepository.com/artifact/org.apache.maven.plugin-tools/maven-plugin-annotations
maven-plugin-annotations = "3.15.2"
# https://mvnrepository.com/artifact/org.codehaus.plexus/plexus-utils
plexus-utils = "4.0.0"
# https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
jacson-databind = "2.16.1"
# https://mvnrepository.com/artifact/org.apache.maven/maven-plugin-api
maven-plugin-api = "3.9.11"
richeditor-compose = "1.0.0-beta02"
uiautomatorV18 = "2.1.3"
window = "1.5.1"


[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-core-animation = { module = "androidx.core:core-animation", version.ref = "coreAnimation" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
androidx-graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "graphicsShapes" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rulesVersion" }
androidx-slice-builders = { module = "androidx.slice:slice-builders", version.ref = "sliceBuilders" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
core = { module = "androidx.core:core", version.ref = "core" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dexmaker-mockito = { module = "com.google.dexmaker:dexmaker-mockito", version.ref = "dexmakerMockito" }
dexmaker = { module = "com.google.dexmaker:dexmaker", version.ref = "dexmaker" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation"}

coil = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
rules = { module = "com.android.support.test:rules", version.ref = "rules" }
runner = { module = "com.android.support.test:runner", version.ref = "runner" }

commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
dom4j = { module = "org.dom4j:dom4j", version.ref = "dom4j" }
json = { module = "org.json:json", version.ref = "json" }
maven-plugin-annotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version.ref = "maven-plugin-annotations" }
jacson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacson-databind" }
maven-plugin-api = { module = "org.apache.maven:maven-plugin-api", version.ref = "maven-plugin-api" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
uiautomator-v18 = { module = "com.android.support.test.uiautomator:uiautomator-v18", version.ref = "uiautomatorV18" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-ksp = "com.google.devtools.ksp:2.3.3"
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
#cash-licensee = { id = "app.cash.licensee", version.ref = "licensee" }
#rikka-refine = { id = "dev.rikka.tools.refine", version.ref = "refine" }
#diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin"}
jetbrainsComposeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
